### ISSUE TITLE
Doesn't notify on PR builds?

### ISSUE THREAD

**Issue by Bauke** [k3rn31p4nic/appveyor-discord-webhook#1]
Let me first say I'm very new to AppVeyor and I'm probably doing something wrong or expecting behaviour that doesn't work.

When merging a branch to master and AppVeyor builds, it'll properly send a notification to Discord however when a PR is submitted and AppVeyor builds, it'll say that `$env:WEBHOOK_URL` isn't passed as the second arg. Yet the log shows it is.

If you'd like to look at the logs (the warning is all the way at the bottom)
* [Successful (master build)](https://ci.appveyor.com/project/Bauke/cash-register/build/1.0.10)
* [Unsuccessful (pr build)](https://ci.appveyor.com/project/Bauke/cash-register/build/1.0.11)

**Comment by iamtraction** [comment]
If the builds are started by a different user, it won't have the secure environment variables, like `WEBHOOK_URL`, available in the build process. That's the reason it's not able to send the webhook, because the `WEBHOOK_URL` environment variables isn't available their builds. That's a security measure to protect your secure environment variables. That's not unique to AppVeyor, Travis CI does that too.

**Comment by Bauke** [comment]
Ah, right! That makes total sense now that I think about it. If they didn't secure it you could just expose the variable and then the secure env variable option has no use. Thanks for the quick response! I guess we'll have to do without PR notifications.

**Comment by iamtraction** [comment]
Yeah. And note that if you start the build, you'll be able to receive webhooks.

I hope that answers your question, and I should now close the issue.
